version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    networks:
      - strapi
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
