version: '3'
services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'

  strapiDB:
    ports:
      - '5432:5432'
